theme: jekyll-theme-leap-day
title: [Библиотека 129 - Медиацентр]
description: [Современная библиотека и медиацентр в районе Марьино. Книги, коворкинг, семейная зона для чтения с детьми, компьютерный и медиа залы. Мы организуем конецерты, выставки и мастер-классы]
